import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const generateMonthlyEODPDF = (report) => {

  const doc = new jsPDF("p", "mm", "a4");

  const { employee, summary, records } = report;

  const pageWidth = doc.internal.pageSize.getWidth();

  // ===========================
  // Header
  // ===========================

  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text(
    "MANAVIYA DRISHTIKON SEVA SAMITI",
    pageWidth / 2,
    12,
    { align: "center" }
  );

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(
    "Salary Management System",
    pageWidth / 2,
    18,
    { align: "center" }
  );

  doc.setDrawColor(180);
  doc.line(15, 22, pageWidth - 15, 22);

  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.text(
    "MONTHLY EOD REPORT",
    pageWidth / 2,
    30,
    { align: "center" }
  );

  // ===========================
  // Employee Information
  // ===========================

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);

  let y = 40;

  doc.text(`Employee Name`, 15, y);
  doc.text(":", 50, y);
  doc.text(employee.name || "-", 55, y);

  y += 6;

  doc.text(`Employee ID`, 15, y);
  doc.text(":", 50, y);
  doc.text(employee.employeeId || "-", 55, y);

  y += 6;

  doc.text(`Department`, 15, y);
  doc.text(":", 50, y);
  doc.text(employee.department || "-", 55, y);

  y += 6;

  doc.text(`Submitted Days`, 15, y);
  doc.text(":", 50, y);
  doc.text(String(summary.submittedDays), 55, y);

  y += 6;

  doc.text(`Manual Entries`, 15, y);
  doc.text(":", 50, y);
  doc.text(String(summary.manualEntries), 55, y);

  y += 6;

  doc.text(`Generated On`, 15, y);
  doc.text(":", 50, y);
  doc.text(
    new Date().toLocaleDateString("en-GB"),
    55,
    y
  );

  // ===========================
  // Table
  // ===========================

  autoTable(doc, {

    startY: y + 8,

    head: [

      [

        "Date",

        "Today's Work"

      ]

    ],

    body: records.map((item) => [

      item.date,

      item.todayWork

    ]),

    theme: "grid",

    styles: {

      font: "helvetica",

      fontSize: 8,

      cellPadding: 2,

      overflow: "linebreak",

      valign: "middle",

    },

    headStyles: {

      fillColor: [37, 99, 235],

      textColor: 255,

      fontStyle: "bold",

      halign: "center",

      fontSize: 9,

    },

    columnStyles: {

      0: {

        cellWidth: 28,

        halign: "center",

      },

      1: {

        cellWidth: "auto",

      },

    },

    margin: {

      left: 15,

      right: 15,

    },

    didDrawPage: function (data) {

      const pageCount = doc.internal.getNumberOfPages();

      doc.setFontSize(8);

      doc.setFont("helvetica", "italic");

      doc.text(

        `Page ${pageCount}`,

        pageWidth - 20,

        doc.internal.pageSize.height - 10

      );

      doc.text(

        "Generated by Salary Management System",

        15,

        doc.internal.pageSize.height - 10

      );

    },

  });

  // ===========================
  // Signature
  // ===========================

  const finalY =
    doc.lastAutoTable.finalY + 18;

  doc.setFontSize(9);

  doc.line(20, finalY, 70, finalY);

  doc.line(
    pageWidth - 70,
    finalY,
    pageWidth - 20,
    finalY
  );

  doc.text(
    "Employee Signature",
    22,
    finalY + 5
  );

  doc.text(
    "Admin Signature",
    pageWidth - 66,
    finalY + 5
  );

  doc.save(
    `${employee.employeeId}-Monthly-EOD.pdf`
  );

};

export default generateMonthlyEODPDF;